# Generated by Django 3.0.3 on 2020-03-13 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScoalaWeb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='post',
            new_name='activitati',
        ),
    ]
